export const SOCKETS_CONNECTED = 'SOCKETS_CONNECTED';
export const SOCKETS_DISCONNECTED = 'SOCKETS_DISCONNECTED';
export const SOCKETS_MESSAGE_RECEIVED = 'SOCKETS_MESSAGE_RECEIVED';
export const SOCKETS_MESSAGE_SENT = 'SOCKETS_MESSAGE_SENT';
export const HISTORY_RECEIVED = 'HISTORY_RECEIVED';
